-- 1. Business Profiles
create table if not exists public.business_profiles (
  id text primary key,
  name text,
  email text,
  phone text,
  type text,
  subscription_plan text,
  is_subscribed boolean,
  password text, 
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.business_profiles disable row level security;

-- 2. Services
create table if not exists public.services (
  id text primary key,
  business_id text references public.business_profiles(id),
  name text,
  price numeric,
  duration_minutes integer,
  description text,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.services disable row level security;

-- 3. Staff
create table if not exists public.staff (
  id text primary key,
  business_id text references public.business_profiles(id),
  name text,
  role text,
  phone text,
  commission_rate numeric,
  status text,
  avatar text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.staff disable row level security;

-- 4. Customers (Global List)
create table if not exists public.all_customers (
  id text primary key,
  business_id text references public.business_profiles(id),
  name text,
  phone text,
  email text,
  total_visits integer default 0,
  loyalty_points integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.all_customers disable row level security;

-- 5. Inventory
create table if not exists public.inventory (
  id text primary key,
  business_id text references public.business_profiles(id),
  name text,
  category text,
  stock integer,
  unit text,
  min_stock_alert integer,
  vendor text,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.inventory disable row level security;

-- 6. Appointments
create table if not exists public.appointments (
  id text primary key,
  business_id text references public.business_profiles(id),
  customer_id text references public.all_customers(id),
  staff_id text references public.staff(id),
  service_id text references public.services(id),
  date text,
  time text,
  status text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.appointments disable row level security;

-- 7. Invoices
create table if not exists public.invoices (
  id text primary key,
  business_id text references public.business_profiles(id),
  appointment_id text references public.appointments(id),
  customer_id text references public.all_customers(id),
  date text,
  amount numeric,
  tax numeric,
  total numeric,
  method text,
  generated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.invoices disable row level security;

-- 8. AI Consultations
create table if not exists public.ai_consultations (
  id bigint generated by default as identity primary key,
  business_id text references public.business_profiles(id),
  customer_name text,
  recommended_services jsonb,
  skin_type text,
  age_group text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.ai_consultations disable row level security;
